### PR TITLE
Build system and other fixes

### PR DESCRIPTION
**Pull request by alexkowalski**
There are some problems with failing builds of the new version under certain conditions, these changes should fix most of those that I am aware of and also include a CI configuration for GitHub Actions that builds w2dynamics and runs the tests using the latest versions of Ubuntu and macOS with both the latest version of Python 3 and of Python 2.

### CODE REVIEW

**Comment by mwallerb** [comment]
Shall we merge this or do you want to do review?

**Comment by alexkowalski** [comment]
If you can take a look at the changes some time soon that would be good, but if not then I think you can just merge it too. Building and testing works on Github Actions and our Gitlab CI, and all the changes concern only the build system (and the README). Under some conditions building the tests (specifically linking the Fortran test executables to the C++ standard library) on Mac apparently still fails, which is not fixed here yet, but at the moment I unfortunately don't know what to do about that either. Ideally there should be some way to have some target linked to the C++ standard library by cmake that works system- and standard library implementation-independently, but I have not found one yet. (It might work most of the time to ask for the C++ compiler to be invoked for linking, but at the moment I specifically request the Fortran compiler to be invoked for linking because otherwise the tests are not linked correctly on our CI image that uses the PGI 17.10 compilers for Fortran and C++ and GCC for C.)

**Comment by alexkowalski** [comment]
Oh, another thing: I think it would also be nice if someone added version tags to the corresponding commits, and while I did already change the displayed version to 1.1.0 in the pull request one week ago, I think it would be better to put 1.1.0 on either the last commit of this pull request or possibly the last of any further build system fixes I might still prepare in the next few days depending on feedback.

**Comment by alexkowalski** [comment]
After recent experiences it seemed to me that our readme was not detailed enough, so I extended and updated it a little bit. I think that it is particularly important that someone else reviews that change because this is pretty much the first thing a potentially interested new user would get to see.

**Comment by CaptainSifff** [comment]
I read the README and it seems great!. If you want you can remind people in the cmake section that the availability of
the --DMYLIB_ROOT=... flags depends on their actual cmake version. Not sure if this makes the initial readme too complicated, though.

**Comment by alexkowalski** [comment]
> I read the README and it seems great!. If you want you can remind people in the cmake section that the availability of
> the --DMYLIB_ROOT=... flags depends on their actual cmake version. Not sure if this makes the initial readme too complicated, though.

@CaptainSifff For NFFT and FFTW at least, I would expect it to work for all versions because we use the CMake modules in our repository in those cases and they should always check the _ROOT paths. For BLAS, LAPACK and HDF5, that might be a problem. If you think that it is likely that someone might encounter this, I could add a short note to the installation section, otherwise I would rather keep this new options/troubleshooting paragraph as short as possible. I only added it because I know that specifying the NFFT path is something that people want to do and it was not documented before, and I think that problems with multiple python installations could likely happen (and there only specifying the interpreter path might not even actually be enough, but I tried to keep it short).

As an alternative, we could also move the descriptions of all the options to some wiki article and just link there, e.g. the installation one, but I would guess that the short new paragraph in the changed README covers the most important obstacles one could encounter during the installation and so I would leave it roughly as it is now until it turns out that people do regularly need or want more details.

**Comment by alexkowalski** [comment]
> Shall we merge this or do you want to do review?

@mwallerb I think it is time to merge this unless there are any issues or someone still wants to do a quick review in the very near future.

**Comment by mwallerb** [comment]
Looks OK to me.  BTW: does this fix the fact that right now, build files leak out of the `build/` directory into the source tree, thereby breaking multiple builds?

**Comment by alexkowalski** [comment]
> Looks OK to me. BTW: does this fix the fact that right now, build files leak out of the `build/` directory into the source tree, thereby breaking multiple builds?

That should already have been fixed in the last update. Do you actually still have this problem with the current master version?

**Comment by mwallerb** [comment]
Ah, I might've missed that update.

**Comment by alexkowalski** [comment]
If you check, can you tell me if you have any problems? There might actually be an issue I just remembered. I think I sometimes had problems with f2py doing nothing if the old extension modules were left in the build directory, so I basically reverted https://github.com/w2dynamics/w2dynamics/commit/ff0178442155f8bf005031ae66a8e6253dee1ee0 only in the gitlab version but did not change it when updating here, but as far as I can tell that is also not really what you asked about because you mention files leaking into the source directory, while this is potentially an issue with files in the build directory. Right now, the build process should only put the CTQMC and MAXENT module files into the source tree which does not cause any problems with subsequent builds (but they would be overwritten during the next build unless you use different Python versions).

**Comment by CaptainSifff** [comment]
@alexkowalski Let's keep it short in that part. People need that information usually quickly.

**Comment by alexkowalski** [comment]
Hey, I don't know if you are waiting for me or why else there has been nothing happening here again for days, but I should maybe mention again that I do not have write access to this repository. Could you actually please just give me write access so I can take care of such things myself faster in the future and also, if there are other permissions needed for that, anything else I might need to manage releases on the repository and edit the wiki? I would then also immediately merge this pull request unless there are any issues with it, but as far as I can see there are none. (If anyone disagrees please make sure the problem actually exists and state the conditions and desired outcome clearly, thanks.)

**Comment by CaptainSifff** [comment]
Hi alex, no need to be impatient; I've merged your fixes and will look for the required permissions.

**Pull request merged**
