### PR TITLE
Make python imports relative

### PR DESCRIPTION
**Pull request by Wentzell**
This pull requests makes all the internal python imports relative.

This will guarantee that the proper imports are picked up no matter what ```os.path``` is set to.

### CODE REVIEW

**Comment by CaptainSifff** [comment]
@mwallerb @sangiova can somebody from the python gurus look at this?

**Comment by alexkowalski** [comment]
@CaptainSifff This does not work in its current state. All the `from ..` imports fail because the top-level source directory is not a package. Also, starting relative imports directly with `import` instead of `from . import` is syntax incompatible with Python 3.

**Comment by Wentzell** [comment]
Hey everyone,

> imports fail because the top-level source directory is not a package

@alexkowalski I actually meant to include a top-level ```__init__.py``` with the Pull-request.

> starting relative imports directly with `import` instead of `from . import` is syntax incompatible with Python 3.

This I was not aware of but that could of course easily be circumvented by rewriting the according import statements.

> This is not a good idea IMHO: relative imports are prone to breaking scripts and are less readable. @Wentzell : What is the rationale for this change?
> 
> Here's a counter-proposal: let's use a top-level package `w2dyn`, and then change the imports to
> `import w2dyn.orbspin` etc? @Wentzell : is this acceptable?

@mwallerb The rationale behind the change is in fact to be able to do a proper install of the w2dynamics package into an encapsulated module at e.g.

```
${CMAKE_INSTALL_PREFIX}/lib/python${PYTHON_VERSION_MAJOR}.${PYTHON_VERSION_MINOR}/site-packages/w2dyn
```

by creating an install target in the top-level ```CMakeLists.txt```

```cmake
# -- Installation                                                                                                                                                                                                                                                                
if((NOT CMAKE_INSTALL_PREFIX_INITIALIZED_TO_DEFAULT) AND (IS_ABSOLUTE ${CMAKE_INSTALL_PREFIX}))                                                                                                                                                                                  
  set(PYTHON_INSTALL_ROOT lib/python${PYTHON_VERSION_MAJOR}.${PYTHON_VERSION_MINOR}/site-packages/w2dyn)                                                                                                                                                                         
  message(STATUS "Installation directory will be ${CMAKE_INSTALL_PREFIX}/${PYTHON_INSTALL_ROOT}")                                                                                                                                                                                
  install(DIRECTORY auxiliaries dmft maxent DESTINATION ${PYTHON_INSTALL_ROOT} FILES_MATCHING PATTERN "*.py" PATTERN "*.so" PATTERN "configspec")                                                                                                                                
  install(FILES __init__.py DESTINATION ${PYTHON_INSTALL_ROOT})                                                                                                                                                                                                                  
endif()
```

I agree that the relative imports are only an intermediate solution to make both setups work, i.e. 

- the current less conventional way of installting the libs/modules back into the
```${CMAKE_SOURCE_DIR}``` without an outer module
- the install into an encapsulated module as described above

**Comment by Wentzell** [comment]
@mwallerb According to our skype discussion I have updated the PR to encapsulate the modules ```auxiliaries```, ```dmft``` and ```maxent``` into an enclosing ```w2dyn``` module.
I have also adjusted all python imports and CMakeFiles accordingly.

**Comment by CaptainSifff** [comment]
Passes our pipelines. If I get no negative feedback we can merge it.

**Pull request merged**
